### ISSUE TITLE
We don't have a logout button for students. 

### ISSUE THREAD

**Issue by tommcandrew** [tommcandrew/quiz-master#34]

**Comment by ZehraRiz** [comment]
The scope of the student's part of the app is very limited. 
Right now the student can use their "one time code" to attempt the quiz, while making sure not to refresh the page. 

The student do not have a proper dashboard or a login id etc, 
We can have a button to go back to login page if they put in an expired code. 

Otherwise for such limited scope, I dont think we need a logout.
