### ISSUE TITLE
How should we send invites to people added later?

### ISSUE THREAD

**Issue by tommcandrew** [tommcandrew/quiz-master#61]
So the teacher will click on "update quiz", then go to Invite and add some more contacts. Then what should they click to send the new invite emails? Should we render a special button e.g. "Send New Invites"?

**Comment by ZehraRiz** [comment]
Even if we make a new button, the data wouldve already been sent to the db before clicking update and theres no way of distinguishing between old and new invites in the db. 

Updating a quiz will also be breaking some other functionalities, 
eg: When we build the functionality of the student's quiz progress being uploaded live to the db, so that he may resume in case of reloads. A student might leave a "no time limit" quiz half done, and resume it the next day, Whearas if the teacher updates the quiz in between that time, the student will be opening a different quiz from the question from where he left. 

If we want to change the db, we can have a new array in the DB of "new invites". which gets empty on each "quiz update/publish" and the data is pushed to the original invites array after new emails sent. Basically DB manipulation 

Another solution to this could be, when we update the quiz, we basically delete the old one, making all the codes and invites void. And every student will be sent a new code and quiz in a new email

Or we can remove the "edit quiz" functionality altogether because it seems to be breaking the app's logic

**Comment by tommcandrew** [comment]
The newInvites array is a good idea. Let's go with that. 

I think being able to edit the quiz is important so let's try to keep it if possible. 

I don't think it's a problem that the quiz could be updated when a student is halfway through. It would be the teacher's responsibility that the update doesn't cause issues.
